"""add_description_field_to_books

Revision ID: cf7d3dd2950e
Revises: 0954e0c5601a
Create Date: 2025-05-25 22:01:47.332053

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf7d3dd2950e"
down_revision: Union[str, None] = "0954e0c5601a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "description")
    # ### end Alembic commands ###
